### ISSUE TITLE
SSH 断开后没有提示

### ISSUE THREAD

**Issue by setncnz** [termix-io/zh#42]

**Comment by wspl** [comment]
断开后显示一个遮罩，加一个断开连接的图标，这样效果怎么样

**Comment by setncnz** [comment]
我觉得可以再加个重新连接的功能

**Comment by CptTZ** [comment]
> 断开后显示一个遮罩，加一个断开连接的图标，这样效果怎么样

或者提供文字说明，表示连接已断开。
也可以在Tab前加绿色/红色的提示标记。

**Comment by kotori2** [comment]
EAP4.0。。太惨了（
