### ISSUE TITLE
新功能建议

### ISSUE THREAD

**Issue by baobao1270** [termix-io/zh#63]
1. 添加黑夜模式
2. Server 可以直接添加在根目录，而不是必须指定文件夹
3. Ctrl-V 直接向服务器发送，而不是“黏贴”
4. Explorer 增加 Git 支持
5. 增加 telnet 支持
6. 能不能有插件功能，可以自己写插件

**Comment by wspl** [comment]
1. 这个已经存在于 EAP3.0 的更新计划中
2. 暂时不考虑，建议创建一个目录当做默认文件夹
3. Ctrl+V 直接发送至服务器是什么意思？如果需要执行一条命令，要求命令的结尾有 \r 来模拟回车动作
4. 这个已经存在于 EAP7.0  的更新计划中
5. 这个已经存在于 EAP8.0 的更新计划中
6. 这个已经存在于 EAP6.0 的更新计划中

**Comment by kotori2** [comment]
3. @wspl 他意思是有些应用需要占用Ctrl+V（就像screen要detatch需要Ctrl+A+D那样），我也觉得复制粘贴的快捷键可以换成Ctrl+Shift+C/Ctrl+Shift+V，这样可能更加贴近程序员的习惯（
