### ISSUE TITLE
[ENHANCEMENT]关闭Preference/服务器配置的时候，如果配置未改变，不提示是否保存

### ISSUE THREAD

**Issue by kotori2** [termix-io/zh#75]

**Comment by wspl** [comment]
这个特性其实是有的，只不过很多配置会在编辑服务器的时候才初始化，第一次保存之后就正常了。

考虑再优化一下，把服务器配置初始化放到新建服务器阶段。

**Comment by kotori2** [comment]
貌似目前有效果，但是只要点一下任意一个输入框，都会引起保存提示

**Comment by wspl** [comment]
这个特性将会一直维持，以保证能够控制功能更新导致的配置文件更新
